name: CVE Binary Tool Scanner
on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '20 2 * * *'
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: intel/cve-bin-tool-action@main
        # with:
        #   nvd_api_key: '${{ secrets.NVD_API_KEY }}'
        #   exclude_dir: test
